name = "GlyphEctoplasm"
uuid = "8227acd8-3ec4-4c13-8000-5272694d2f9b"
authors = ["Shane Kuei-Hsien Chu (skchu@wustl.edu)"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EntroPlots = "742586e2-2ccd-48a5-bc1c-31de6daa8fd7"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SEQ2EXPdata = "321b9d11-aa10-4af3-aaad-5d74081bdd4f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10.15"
CairoMakie = "0.15.6"
DataFrames = "1.8.1"
EntroPlots = "0.1.9"
FileIO = "1.17.1"
JSON3 = "1.14.3"
Mustache = "1.0.21"
ProgressMeter = "1.11.0"
SEQ2EXPdata = "1.0.4"
Statistics = "1.11.1"
StatsBase = "0.34.8"
julia = "1.11.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
